name: backend

on:
  pull_request:

jobs:
  symbolicator:
    name: symbolicator test
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          # Avoid codecov error message related to SHA resolution:
          # https://github.com/codecov/codecov-bash/blob/7100762afbc822b91806a6574658129fe0d23a7d/codecov#L891
          fetch-depth: '2'

      - name: Setup sentry env
        uses: ./.github/actions/setup-sentry
        id: setup
        with:
          snuba: true
          kafka: true
          symbolicator: true

      - name: /etc/hosts
        run: |
            echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts

      - name: Run test
        run: |
          pytest tests/symbolicator/test_payload_full.py::SymbolicatorResolvingIntegrationTest::test_real_resolving
